Final/Final/Models/Comment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Final.Models
{
    public class Comment
    {
        public int Id { get; set; }

        public virtual Picture Picture { get; set; }
        public int PictureId { get; set; }

        
        public string Writer { get; set; }

        public string Text { get; set; }

        public DateTime Date { get; set; }

        public string Pic { get; set; }

    }
}

Final/Final/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Final.Models;
using Final.Context;

namespace Final.Controllers
{
    public class CommentController : Controller
    {
        private WebContext db = new WebContext();

        // GET: /Comment/
        public ActionResult Index(Comment comment)
        {

            var comments = db.Comments.Where(s => s.PictureId.Equals(comment.PictureId));
            return View(comments.ToList());
        }
        public ActionResult Search(string Text)
        {

            var comments = from m in db.Comments
                           select m;

            if (!String.IsNullOrEmpty(Text))
            {
                comments = comments.Where(s => s.Text.Contains(Text));
            }
            return View("Index", comments);
        }
        // GET: /Comment/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var comment = db.Comments.Where(x => x.PictureId == id);
            if (comment == null)
            {
                return HttpNotFound();
            }

            return View("Index", comment);
        }

        // GET: /Comment/Create
        public ActionResult Create()
        {
            ViewBag.PictureId = new SelectList(db.Pictures, "Id", "FileName");
            return View();
        }
        public ActionResult AddComment(int id)
        {
            var Comment = new Comment
            {
                PictureId = id,
                Date = DateTime.Now
            };

            ViewBag.PictureId = new SelectList(db.Pictures, "Id", "FileName");

            return View("Create", Comment);
        }

        // POST: /Comment/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,PictureId,Writer,Text,Date,Pic")] Comment comment)
        {
            if (ModelState.IsValid)
            {
                comment.Pic = (from a in db.Artists
                               where a.Name.Equals(User.Identity.Name)
                               select a.UserProfilePic).FirstOrDefault();
                comment.Writer = User.Identity.Name;
                comment.Date = DateTime.Now;

                db.Comments.Add(comment);
                db.SaveChanges();

                return RedirectToAction("Index", comment);
            }

            ViewBag.PictureId = new SelectList(db.Pictures, "Id", "FileName", comment.PictureId);
            return View("Index", comment);
        }

        // GET: /Comment/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            ViewBag.PictureId = new SelectList(db.Pictures, "Id", "FileName", comment.PictureId);
            return View(comment);
        }

        // POST: /Comment/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,PictureId,Picture,Writer,Text,Pic")] Comment comment)
        {
            if (ModelState.IsValid)
            {
                comment.Date = DateTime.Now;
                comment.Writer = User.Identity.Name;
                comment.Pic = (from a in db.Artists
                               where a.Name.Equals(User.Identity.Name)
                               select a.UserProfilePic).FirstOrDefault();
                db.Entry(comment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details", new {id = comment.PictureId });
            }
            ViewBag.PictureId = new SelectList(db.Pictures, "Id", "FileName", comment.PictureId);
            return View("Artist");
        }

        // GET: /Comment/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        // POST: /Comment/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Comment comment = db.Comments.Find(id);
            var tempId = comment.PictureId;
            db.Comments.Remove(comment);
            db.SaveChanges();
            return RedirectToAction("Details", new {id = tempId });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Final/Final/Controllers/PictureController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Final.Models;
using Final.Context;
using System.IO;

namespace Final.Controllers
{
    public class PictureController : Controller
    {
        private WebContext db = new WebContext();

        // GET: /Picture/
        public ActionResult Index()
        {
            var pictures = db.Pictures.Include(p => p.Artist).Include(p => p.Genre).Include(p => p.PictureType);
            return View(pictures.ToList());
        }

        public ActionResult Search(string Name , string SearchGenre, int? Price = 0)
        {
           
            var pictures = from m in db.Pictures
                           select m;

            if (!string.IsNullOrEmpty(SearchGenre))
            {
                pictures = pictures.Where(x => x.Genre.Name.ToLower().Contains(SearchGenre.ToLower()));
            }


            if (!string.IsNullOrEmpty(Name))
            {
                pictures = pictures.Where(x => x.FileName.ToLower().Substring(0,x.FileName.Length - 4).Contains(Name.ToLower()));
            }


            if(Price != 0)
            {
                pictures = pictures.Where(x => x.Price >= Price);
            }

            return View("Index", pictures);
        }

        public ActionResult The3MostPopularGenres()
        {
            var top3 = db.Pictures
                .GroupBy(q => q.GenreId)
                .OrderByDescending(group => group.Count())
                //.Select(g => g.Key);
                .Take(3)
                .Select(x => x.Key);
            //.ToList();
            var groups = from p in db.Pictures
                         where top3.Contains(p.GenreId)
                         select p;


            return View("index", groups);

        }
        // GET: /Picture/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var picture = db.Pictures.Where(x => x.ArtistId == id);

            if (picture == null)
            {
                return HttpNotFound();
            }
            return View("Index", picture);
        }

        public ActionResult PictureDetails(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var picture = db.Pictures.Where(x => x.Id == id);

            if (picture == null)
            {
                return HttpNotFound();
            }
            return View("Index", picture);
        }

        // GET: /Picture/Create
        public ActionResult Create()
        {
            ViewBag.ArtistId = new SelectList(db.Artists, "Id", "Name");
            ViewBag.GenreId = new SelectList(db.Genres, "Id", "Name");
            ViewBag.PictureTypeId = new SelectList(db.PictureTypes, "Id", "Name");
            return View();
        }

        // GET: /Picture/AddPicture
        public ActionResult AddPicture(int id)
        {
            var picture = new Picture
            {
                ArtistId = id,
                PictureTypeId = (int)EPictureType.Image
            };

            ViewBag.ArtistId = new SelectList(db.Artists, "Id", "Name");
            ViewBag.GenreId = new SelectList(db.Genres, "Id", "Name");
            ViewBag.PictureTypeId = new SelectList(db.PictureTypes, "Id", "Name");

            return View("Create", picture);
        }

        // POST: /Picture/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,FileName,PictureTypeId,ArtistId,Price,GenreId,Description")] Picture picture, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                for (int i = 0; i < Request.Files.Count; i++)
                {
                    HttpPostedFileBase file = Request.Files[i];
                    if (file != null && file.ContentLength > 0)
                    {
                        picture.FileName = file.FileName;
                        file.SaveAs(Path.Combine(Server.MapPath("~/Pictures/"), picture.FileName));
                    }
                }
                db.Pictures.Add(picture);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ArtistId = new SelectList(db.Artists, "Id", "Name", picture.ArtistId);
            ViewBag.GenreId = new SelectList(db.Genres, "Id", "Name", picture.GenreId);
            ViewBag.PictureTypeId = new SelectList(db.PictureTypes, "Id", "Name", picture.PictureTypeId);
            return View(picture);
        }

        // GET: /Picture/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Picture picture = db.Pictures.Find(id);
            if (picture == null)
            {
                return HttpNotFound();
            }
            ViewBag.ArtistId = new SelectList(db.Artists, "Id", "Name", picture.ArtistId);
            ViewBag.GenreId = new SelectList(db.Genres, "Id", "Name", picture.GenreId);
            ViewBag.PictureTypeId = new SelectList(db.PictureTypes, "Id", "Name", picture.PictureTypeId);
            return View(picture);
        }

        // POST: /Picture/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,FileName,PictureTypeId,ArtistId,Price,GenreId,Description")] Picture picture)
        {
            if (ModelState.IsValid)
            {
                db.Entry(picture).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ArtistId = new SelectList(db.Artists, "Id", "Name", picture.ArtistId);
            ViewBag.GenreId = new SelectList(db.Genres, "Id", "Name", picture.GenreId);
            ViewBag.PictureTypeId = new SelectList(db.PictureTypes, "Id", "Name", picture.PictureTypeId);
            return View(picture);
        }

        // GET: /Picture/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Picture picture = db.Pictures.Find(id);
            if (picture == null)
            {
                return HttpNotFound();
            }
            return View(picture);
        }

        // POST: /Picture/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Picture picture = db.Pictures.Find(id);
            var comments = (from comment in db.Comments
                            where comment.PictureId == picture.Id
                            select comment).ToList();
            foreach (var c in comments)
            {
                db.Comments.Remove(c);
            }

            db.Pictures.Remove(picture);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult FindDate(string Date)
        {
            DateTime date = Convert.ToDateTime(Date);
            var query = from picture in db.Pictures
                        join comment in db.Comments on picture.Id equals comment.PictureId
                        where DateTime.Compare(comment.Date, date) == 1
                        select picture;
            return View("Index", query.Distinct());
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Final/Final/Views/Comment/Create.cshtml
@model Final.Models.Comment

@{
    ViewBag.Title = "Create";
}


<!-- Page Title -->
<div class="section section-breadcrumbs ">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1>Add comment</h1>
            </div>
        </div>
    </div>
</div>



@using (Html.BeginForm("Create", "Comment", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        
        @Html.ValidationSummary(true)
        <div class="form-group">
            @Html.HiddenFor(model => model.PictureId)
            @Html.HiddenFor(model => model.Date)
            @Html.HiddenFor(model => model.Writer)
        </div>
        

        <div class="form-group">
            @Html.LabelFor(model => model.Text, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Text)
                @Html.ValidationMessageFor(model => model.Text)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", "Artist")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Final/Final/Views/Comment/Delete.cshtml
@model Final.Models.Comment
@{
    ViewBag.Title = "Delete";
}


<!-- Page Title -->
<div class="section section-breadcrumbs ">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1>Delete comment</h1>
            </div>
        </div>
    </div>
</div>

<h3>Are you sure you want to delete this?</h3>
<div>
    
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Picture.FileName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Picture.FileName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pic)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pic)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Text)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Text)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Details", new {id = Model.PictureId })
        </div>
    }
</div>

Final/Final/Views/Comment/Details.cshtml
@model Final.Models.Comment
@{
    ViewBag.Title = "Details";
}

<!-- Page Title -->
<div class="section section-breadcrumbs ">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1>Details</h1>
            </div>
        </div>
    </div>
</div>

<div>
  
   
    <dl class="dl-horizontal">
       
        <dt>
            @Html.DisplayNameFor(model => model.Picture.FileName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Picture.FileName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Writer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Writer)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Text)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Text)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>
        
    </dl>
</div>

<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Final/Final/Views/Comment/Edit.cshtml
@model Final.Models.Comment

<!-- Page Title -->
<div class="section section-breadcrumbs ">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1>Edit comment</h1>
            </div>
        </div>
    </div>
</div>



@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.PictureId)
        
        <div class="form-group">
            @Html.LabelFor(model => model.Text, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Text)
                @Html.ValidationMessageFor(model => model.Text)
            </div>
        </div>

       

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Details", new {id = Model.PictureId })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Final/Final/Views/Comment/Index.cshtml
@model IEnumerable<Final.Models.Comment>

@{
    ViewBag.Title = "Comments";
}




<!-- Page Title -->
<div class="section section-breadcrumbs ">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1>Comments</h1>
            </div>
        </div>
    </div>
</div>



<div class="container">
    <div class="row">

        @foreach (var item in Model)
        {
            <div class="row">
                <div class="col-md-4">
                    <div class="img-thumbnail">
                        <img class="img-responsive user-photo" src="~/Pictures/@Html.DisplayFor(ModelItem => item.Picture.FileName)">

                    </div>
                </div>
            </div>
            break;
        }
        <br />
        <br />

        <div class=" col-md-8 faq-wrapper">
            @foreach (var item in Model)
            {

                <div class="row">
                    <div class="col-md-1">
                        <div class="thumbnail">
                            
                                <img class="img-responsive user-photo" src="~/Pictures/@Html.DisplayFor(modelItem => item.Pic)">
                            
                        </div><!-- /thumbnail -->
                        </div><!-- /col-sm-1 -->

                        <div class="col-md-10">
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    <strong>@Html.DisplayFor(modelItem => item.Writer)</strong> <span class="text-muted">commented on: @Html.DisplayFor(modelItem => item.Date)</span>
                                    @if (User.Identity.Name.Equals("admin") || (User.Identity.Name.Equals(item.Writer)))
                                    {
                                        @Html.ActionLink("Edit |", "Edit", new { id= item.Id})
                                        @Html.ActionLink(" Delete ", "Delete", new { id = item.Id })
                                    }
                                </div>
                                <div class="panel-body">
                                    @Html.DisplayFor(modelItem => item.Text)
                                </div><!-- /panel-body -->
                            </div><!-- /panel panel-default -->
                        </div><!-- /col-sm-5 -->
                    </div><!-- /row -->
                    }


                </div>
        <!-- Sidebar -->
                <div class="col-md-4 blog-sidebar">
                    <h4>Search our Blog</h4>

                    <div class="input-group ">
                        @using (Html.BeginForm("Search", "Comment", FormMethod.Get))
                {
                            <p>
                                Text:<br /> @Html.TextArea("Text")<br /><br />
                                <input class="btn btn-md" type="submit" value="Filter" />
                            </p>
                }


                    </div>
                </div>
            </div>


        </div><!-- /container -->

        <p>
            @Html.ActionLink("Back to List", "Index", "Picture")
        </p>