Final/Final/Models/Artist.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Final.Models
{
    public class Artist
    {
        public Artist()
        {
            Pictures = new HashSet<Picture>();
        }

        public int Id { get; set; }

        public string Name { get; set; }

        public string AboutMe { get; set; }

        public Gender Gender { get; set; }
        public int GenderID { get; set; }

        [Range(0, 120)]
        public int Age { get; set; }

        [RegularExpression(@"^[a-zA-Z]+[ a-zA-Z-_]*$", ErrorMessage = "Use Characters only")]
        public string Address { get; set; }


       [RegularExpression(@"^[a-zA-Z]+[ a-zA-Z-_]*$", ErrorMessage = "Use Characters only")]
        public string City { get; set; }

        public string UserProfilePic { get; set; }

        [EmailAddress]
        public string Mail { get; set; }

        public virtual ICollection<Picture> Pictures { get; set; }
    }
}

Final/Final/Controllers/ArtistController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Final.Models;
using Final.Context;
using System.IO;

namespace Final.Controllers
{
    public class ArtistController : Controller
    {
        private WebContext db = new WebContext();

        // GET: /Artist/
        public ActionResult Index()
        {
            var artists = db.Artists.Include(a => a.Gender);
            return View(artists.ToList());
        }

        // GET: /Artist/
        public ActionResult Login()
        {
            return View(new UserAccount());
        }

       

        public ActionResult Search(string SearchCity, string searchString, int? age)
        {

            var artists = from m in db.Artists
                          select m;

            if (!String.IsNullOrEmpty(searchString))
            {
                artists = artists.Where(s => s.Name.Contains(searchString));

            }
            if (!string.IsNullOrEmpty(SearchCity))
            {
                artists = artists.Where(x => x.City.Contains(SearchCity));
            }
            if (age >= 1)
            {
                artists = artists.Where(x => x.Age >= age);
            }

            return View("Index", artists);
        }
        
        

        public ActionResult FindPrice(int ? price)
        {
            var artists = from m in db.Artists select m;
            if (price >= 1)
            {

                var query = from artist in db.Artists
                            join picture in db.Pictures on artist.Id equals picture.ArtistId
                            where picture.Price > price
                            select artist;

                return View("Index", query.Distinct());
            }
            return View("index", artists);
        }

        // GET: /Artist/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Artist artist = db.Artists.Find(id);
            if (artist == null)
            {
                return HttpNotFound();
            }
            return View(artist);
        }

        // GET: /Artist/Create
        public ActionResult Create()
        {
            ViewBag.GenderID = new SelectList(db.Genders, "Id", "Name");
            return View();
        }

        // POST: /Artist/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,AboutMe,GenderID,Age,Address,City,Mail,UserProfilePic")] Artist artist, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                for (int i = 0; i < Request.Files.Count; i++)
                {
                    HttpPostedFileBase file = Request.Files[i];
                    if (file != null && file.ContentLength > 0)
                    {
                        artist.UserProfilePic = file.FileName;
                        file.SaveAs(Path.Combine(Server.MapPath("~/Pictures/"), artist.UserProfilePic));
                    }
                }
                if(artist.UserProfilePic==null)
                {
                    artist.UserProfilePic = "avatar_2x.png";
                }
                artist.Name = User.Identity.Name;
                db.Artists.Add(artist);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.GenderID = new SelectList(db.Genders, "Id", "Name", artist.GenderID);
            return View(artist);
        }


        // GET: /Artist/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Artist artist = db.Artists.Find(id);
            if (artist == null)
            {
                return HttpNotFound();
            }
            ViewBag.GenderID = new SelectList(db.Genders, "Id", "Name", artist.GenderID);
            return View(artist);
        }

        // POST: /Artist/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,AboutMe,GenderID,Age,Address,City,Mail")] Artist artist, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                for (int i = 0; i < Request.Files.Count; i++)
                {
                    HttpPostedFileBase file = Request.Files[i];
                    if (file != null && file.ContentLength > 0)
                    {
                        artist.UserProfilePic = file.FileName;
                        file.SaveAs(Path.Combine(Server.MapPath("~/Pictures/"), artist.UserProfilePic));
                    }
                }
                db.Entry(artist).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.GenderID = new SelectList(db.Genders, "Id", "Name", artist.GenderID);
            return View(artist);
        }

        // GET: /Artist/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Artist artist = db.Artists.Find(id);
            if (artist == null)
            {
                return HttpNotFound();
            }
            return View(artist);
        }

        // POST: /Artist/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Artist artist = db.Artists.Find(id);
            var pictures = (from picture in db.Pictures
                            where picture.ArtistId == artist.Id
                            select picture).ToList();
            foreach (var p in pictures)
            {
                var comments = (from comment in db.Comments
                                where comment.PictureId == p.Id
                                select comment).ToList();
                foreach (var c in comments)
                {
                    db.Comments.Remove(c);
                }

                db.Pictures.Remove(p);
            }
            db.Artists.Remove(artist);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult getAddress()
        {
            List<String> address = new List<string>();
            string fullAddr;
            var artists = from s in db.Artists select s;
            foreach (var artist in artists)
            {
                if (artist.Address != null)
                {
                    fullAddr = artist.City + " " + artist.Address;
                    address.Add(fullAddr);
                }
            }

            return Json(address, JsonRequestBehavior.AllowGet);
        }

       


        public JsonResult getArtistAndPic()
        {
            
            List<PieChart> ArtistAndPic = new List<PieChart>();
            
            var artists = (from s in db.Artists select s );
            var random = new Random();
            foreach (var artist in artists)
            {
                
                var color = String.Format("#{0:X6}", random.Next(0x1000000));
                var highlight = String.Format("#{0:X6}", random.Next(0x1000000));
                
                if (artist.Pictures.Count() > 0)
                {
                    PieChart pie = new PieChart();

                    pie.label = artist.Name;
                    pie.value = artist.Pictures.Count();
                    pie.color = color;
                    pie.highlight = highlight;
                    
                    ArtistAndPic.Add(pie);

                   
                }
            }
            

            return Json(ArtistAndPic.ToList(), JsonRequestBehavior.AllowGet);
        }

         public JsonResult getArtistAndGender()
        {
            RadarChart radar = new RadarChart();
            RAdarDataSet dataSet = new RAdarDataSet();
            List<RadarChart> radars = new List<RadarChart>();
             List<String> labels = new List<string>();
            List<int> intset = new List<int>();

             var pictures = (from pic in db.Pictures select pic );

             foreach (var picture in pictures){
                 if (picture.Genre.Name != null)
                 {
                      
                     if (!labels.Contains(picture.Genre.Name))
                     {
                         labels.Add(picture.Genre.Name);
                     }
                 }
             }
             dataSet.labels = labels;

             radar.label = "My First dataset";
             radar.fillColor = "rgba(151,187,205,0.2)";
             radar.strokeColor = "rgba(151,187,205,1)";
             radar.pointColor = "rgba(151,187,205,1)";
             radar.pointHighlightFill = "#fff";
             radar.pointStrokeColor = "#fff";
             radar.pointHighlightStroke = "rgba(151,187,205,1)";

             foreach (var genre in dataSet.labels)
             {
                 var count = (from gen in db.Pictures 

Final/Final/Views/Artist/Create.cshtml
@model Final.Models.Artist

@{
    ViewBag.Title = "Create";
}

<!-- Page Title -->
<div class="section section-breadcrumbs">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1>Register cont.</h1>
            </div>
        </div>
    </div>
</div>



@using (Html.BeginForm("Create", "Artist", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
       
        <div class="form-group">
            @Html.LabelFor(model => model.GenderID, "Gender", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("GenderID", String.Empty)
                @Html.ValidationMessageFor(model => model.GenderID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Age, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Age)
                @Html.ValidationMessageFor(model => model.Age)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address)
                @Html.ValidationMessageFor(model => model.Address)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City)
                @Html.ValidationMessageFor(model => model.City)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mail, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Mail)
                @Html.ValidationMessageFor(model => model.Mail)
            </div>
        </div>
        @Html.ValidationSummary(true)
        <div class="form-group">
            @Html.LabelFor(model => model.AboutMe, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.AboutMe)
                @Html.ValidationMessageFor(model => model.AboutMe)
            </div>
        </div>

        <div class="form-group">
            @Html.Label("upload", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="upload" required />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Final/Final/Views/Artist/Delete.cshtml
@model Final.Models.Artist

<!-- Page Title -->
<div class="section section-breadcrumbs">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1>Delete confirmation</h1>
            </div>
        </div>
    </div>
</div>

<h3>Are you sure you want to delete this artist?</h3>
<div>
        <hr />
    <dl class="dl-horizontal">
       
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Age)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Age)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City) | @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Mail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mail)
        </dd>

    </dl>
    <br />
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Final/Final/Views/Artist/Details.cshtml
@model Final.Models.Artist

@{
    ViewBag.Title = "Details";
}

<!-- Page Title -->
<div class="section section-breadcrumbs">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1>Artist Details</h1>
            </div>
        </div>
    </div>
</div>





<div class="section">
    <div class="container">
        <div class="row">
            <!-- Product Image -->
            <!--If the artist got an image-->
            @if (Model.Pictures.Count() != 0)
            {
                <div class="col-md-6">
                    
                        <img class=" img-thumbnail" src="~/Pictures/@Html.DisplayFor(model => model.Pictures.First().FileName) " alt="Item Name">
                    
                </div>
            }
            else
            {
                <div class="col-md-6">
                    <div class="img-thumbnail">
                        <img src="https://ssl.gstatic.com/accounts/ui/avatar_2x.png" alt="Item Name">
                    </div>
                </div>
            }

            <!-- End Product Image & Available Colors -->
            <!-- Product Summary & Options -->
            @if (Model.Pictures.Count() != 0)
            {
                <div class="col-md-6 product-details">
                    <h4>@Html.DisplayFor(model => model.Name)'s favorit image</h4>
                    <div class="price">
                        <span class="price-was"> $999.99</span>@Html.DisplayFor(model => model.Pictures.First().Price)
                    </div>
                </div>
            }
            
        </div>
    </div>
</div>
<!-- Full Description & Specification -->
<div class="col-sm-12">
    <div class="tabbable">
        <!-- Tabs -->
        <ul class="nav nav-tabs product-details-nav">
            <li class="active"><a href="#tab1" data-toggle="tab">About me</a></li>
            <li><a href="#tab2" data-toggle="tab">My prices</a></li>
        </ul>
        <!-- Tab Content (Full Description) -->
        <div class="tab-content product-detail-info">
            <div class="tab-pane active" id="tab1">
                <h4>About me</h4>
                <p>
                    @Html.DisplayFor(model => model.AboutMe)
                </p>

                <h4>Details</h4>
                <table>
                    <tr>
                        <td>@Html.DisplayNameFor(model => model.Name)</td>
                        <td>@Html.DisplayFor(model => model.Name)</td>
                    </tr>

                    <tr>
                        <td> @Html.DisplayNameFor(model => model.Age)</td>
                        <td>@Html.DisplayFor(model => model.Age)</td>
                    </tr>
                    <tr>
                        <td>@Html.DisplayNameFor(model => model.Address)</td>
                        <td>@Html.DisplayFor(model => model.Address) | @Html.DisplayFor(model => model.City)</td>
                    </tr>
                    <tr>
                        <td>@Html.DisplayNameFor(model => model.Mail)</td>
                        <td>@Html.DisplayFor(model => model.Mail)</td>
                    </tr>
                </table>
            </div>

            <!-- Tab pictures and prices -->
            <div class="tab-pane" id="tab2">

                @foreach (var item in Model.Pictures)
                {
                    <hr />
                    <table>
                        <tr>
                            <td>Name of the picture : @Html.DisplayFor(modelItem => item.FileName)</td>
                            <td>Price: @Html.DisplayFor(modelItem => item.Price)</td>
                        </tr>
                    </table>
                }
            </div>
        </div>
    </div>
</div>
<!-- End Tab pictures and prices-->


<p>
    @Html.ActionLink("Back to List", "Index")
</p>

Final/Final/Views/Artist/Edit.cshtml
@model Final.Models.Artist

<!-- Page Title -->
<div class="section section-breadcrumbs ">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1>Edit Artist</h1>
            </div>
        </div>
    </div>
</div>

@using (Html.BeginForm("Edit", "Artist", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
       
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="AboutMe">About Me</label>

            <div class="col-md-10">
                @Html.TextAreaFor(model => model.AboutMe)
                @Html.ValidationMessageFor(model => model.AboutMe)
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="GenderID">Gender</label>
            
            <div class="col-md-10">
                @Html.DropDownList("GenderID", String.Empty)
                @Html.ValidationMessageFor(model => model.GenderID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Age, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Age)
                @Html.ValidationMessageFor(model => model.Age)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address)
                @Html.ValidationMessageFor(model => model.Address)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City)
                @Html.ValidationMessageFor(model => model.City)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mail, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Mail)
                @Html.ValidationMessageFor(model => model.Mail)
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2" for="UserProfilePic">Profile picture</label>
            
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserProfilePic)
                @Html.ValidationMessageFor(model => model.UserProfilePic)
            </div>
        </div>

        <div class="form-group">
            @Html.Label("upload", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="Photo" name="upload" required />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Final/Final/Views/Artist/Index.cshtml
@model IEnumerable<Final.Models.Artist>

@{
    ViewBag.Title = "Index";
}

    <!-- Page Title -->
    <div class="section section-breadcrumbs">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h1>All Artists</h1>
                </div>
            </div>
        </div>
    </div>

   

    <div class="section">
        <div class="container">
            <div class="row">
                <div class="col-md-8 faq-wrapper">
                   
                    @foreach (var item in Model)
                    {


                        <div class="panel-group" id="accordion2">
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#@Html.DisplayFor(modelItem => item.Id)">
                                        The Artist @Html.DisplayFor(modelItem => item.Name)<br /><br />

                                        @if (User.Identity.Name.Equals("admin"))
                                        {
                                            @Html.ActionLink("Edit |", "Edit", new { id = item.Id })
                                            @Html.ActionLink(" Delete |", "Delete", new { id = item.Id })
                                        }
                                        @Html.ActionLink("Details", "Details", new { id = item.Id }) |

                                        @if (User.Identity.Name.Equals(item.Name))
                                        {
                                            @Html.ActionLink("Edit |", "Edit", new { id = item.Id })
                                            @Html.ActionLink(" Add picture |", "AddPicture", "Picture", new { id = item.Id }, null)
                                        }
                                        @Html.ActionLink("View All pictures ", "Details", "Picture", new { id = item.Id }, null)

                                    </a>
                                </div>
                                <div id="@Html.DisplayFor(modelItem => item.Id)" class="accordion-body collapse">
                                    <div class="accordion-inner">
                                        <div class="answer">Info:</div>
                                        <p>
                                            Name: @Html.DisplayFor(modelItem => item.Name) |
                                            Age:  @Html.DisplayFor(modelItem => item.Age) |

                                            
                                            Location: @Html.DisplayFor(modelItem => item.Address) | @Html.DisplayFor(modelItem => item.City)
                                        </p>
                                        <div class="=container">


                                            <div class="row">
                                                <div class=" col-md-4">
                                                    <ul class="thumbnails">


                                                            <li class="span4"> ProfilePic:  <img src="~/Pictures/@Html.DisplayFor(modelItem => item.UserProfilePic)" class="thumbnail" width="100" height="90" /></li>
                                                        

                                                    </ul>
                                                </div>
                                            </div>


                                        </div>
                                    </div>
                                </div>

                            </div>

                        </div>

                    }
                </div>


                    <!-- Sidebar -->
                    <div class="col-md-4 blog-sidebar">
                        <h4>Search our Blog</h4>

                        <div class="input-group ">
                            @using (Html.BeginForm("FindPrice", "Artist", FormMethod.Get))
                            {
                                <div class="span4">
                                    <p>

                                        Pictures that cost more than: <br /> @Html.TextBox("price")<br /><br />
                                        <input class="btn btn-md" type="submit" value="Filter" />
                                    </p>
                                </div>
                            }
                        </div>

                    <div class="input-group">
                        @using (Html.BeginForm("Search", "Artist", FormMethod.Get))
                        {
                            <p>
                                City:<br /> @Html.TextBox("SearchCity")<br />
                                Name:<br /> @Html.TextBox("SearchString")<br />
                                From Age: <br />@Html.TextBox("age")<br /><br />

                                <input class="btn btn-md" type="submit" value="Filter" />
                            </p>
                        }
                    </div>
                </div>
            </div>

        </div>
    </div>